version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - tasknet

  frontend:
    build:
      context: ./frontenid/taskui
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tasknet

networks:
  tasknet:
    driver: bridge

